let serverMode=false,cache=null;
function val(id){const e=document.getElementById(id);return e?e.value.trim():''}
function set(id,v){const e=document.getElementById(id);if(e)e.value=v||''}
function showToast(msg){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function toggleSidebar(){const s=document.getElementById('adminSidebar');const b=document.getElementById('sidebarBackdrop');if(!s)return;s.classList.toggle('open');if(b)b.classList.toggle('show',s.classList.contains('open'))}
function closeSidebar(){const s=document.getElementById('adminSidebar');const b=document.getElementById('sidebarBackdrop');if(s)s.classList.remove('open');if(b)b.classList.remove('show')}
function showPanel(id){closeSidebar();document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.sidebar button').forEach(b=>b.classList.remove('active'));const p=document.getElementById('panel-'+id);if(p)p.classList.add('active');const btn=document.querySelector('.sidebar button[data-panel="'+id+'"]');if(btn)btn.classList.add('active')}
async function login(){const pw=document.getElementById('password').value;try{const ok=await TEG.loginServer(pw);if(ok){serverMode=true;sessionStorage.setItem('teg_admin',pw);document.getElementById('loginScreen').classList.add('hidden');document.getElementById('dashboard').classList.add('active');document.getElementById('serverBadge').style.display='inline-block';await load();return}}catch(e){}document.getElementById('loginHint').textContent='Wrong password or server offline'}
function logout(){sessionStorage.removeItem('teg_admin');location.reload()}
async function load(){let data=null;if(serverMode){try{data=await TEG.loadContentServer()}catch(e){}}if(!data){try{data=JSON.parse(localStorage.getItem('teg_content')||'null')}catch(e){}}if(data){cache=data;fill(data)}document.getElementById('connStatus').textContent=serverMode?'Connected to server':'Local only'}
function fill(d){const b=d.branding||{},m=d.media||{},c=d.contact||{},s=d.seo||{},loc=d.location||{};set('brand-siteName',b.siteName);set('brand-logoMark',b.logoMark);set('brand-logoText',b.logoText);set('media-logo',m.logo||b.logoUrl||'');set('media-favicon',m.favicon||b.faviconUrl||'');set('media-heroImage',m.heroImage);set('media-heroVideo',m.heroVideo);set('media-heroPoster',m.heroPoster);set('media-ogImage',m.ogImage);set('media-aboutImage',m.aboutImage);const pm=d.pageMedia||{};set('pm-services',(pm['services.html']||{}).heroImage||'');set('pm-areas',(pm['areas.html']||{}).heroImage||'');set('pm-about',(pm['about.html']||{}).heroImage||'');set('pm-faq',(pm['faq.html']||{}).heroImage||'');set('pm-contact',(pm['contact.html']||{}).heroImage||'');set('contact-phone',c.phone);set('contact-phoneTel',c.phoneTel);set('contact-whatsapp',c.whatsapp);set('contact-whatsappDigits',c.whatsappDigits);set('contact-email',c.email);set('contact-address',c.address);set('contact-addressLine1',c.addressLine1);set('contact-city',c.city);set('contact-region',c.region);set('contact-postal',c.postal);set('contact-hours',c.hours);set('seo-title',s.title);set('seo-description',s.description);set('seo-keywords',s.keywords);set('seo-canonical',s.canonical);set('seo-ogTitle',s.ogTitle);set('seo-ogDescription',s.ogDescription);set('seo-ogImage',s.ogImage);set('seo-twitterTitle',s.twitterTitle);set('seo-twitterDescription',s.twitterDescription);set('seo-twitterImage',s.twitterImage);set('loc-name',loc.name);set('loc-address',loc.address);set('loc-city',loc.city);set('loc-region',loc.region);set('loc-postal',loc.postal);set('loc-lat',loc.lat);set('loc-lng',loc.lng);set('loc-geoRegion',loc.geoRegion);window._servicesCache=Array.isArray(d.services)?JSON.parse(JSON.stringify(d.services)):[];renderServices(d.services||[]);renderNav('main',(d.nav||{}).main);renderNav('footer',(d.nav||{}).footer);renderNav('services',(d.nav||{}).services);window._pagesSeo=d.pages||{};loadPageSeoFields()}
function collect(){const data=cache?JSON.parse(JSON.stringify(cache)):{};data.branding={siteName:val('brand-siteName'),logoMark:val('brand-logoMark'),logoText:val('brand-logoText'),logoUrl:val('media-logo'),faviconUrl:val('media-favicon')};data.media={logo:val('media-logo'),favicon:val('media-favicon'),heroImage:val('media-heroImage'),heroVideo:val('media-heroVideo'),heroPoster:val('media-heroPoster'),ogImage:val('media-ogImage'),aboutImage:val('media-aboutImage')};data.pageMedia=Object.assign({},(cache&&cache.pageMedia)||{},{'services.html':{heroImage:val('pm-services')},'areas.html':{heroImage:val('pm-areas')},'about.html':{heroImage:val('pm-about')},'faq.html':{heroImage:val('pm-faq')},'contact.html':{heroImage:val('pm-contact')}});try{syncBaFromDom()}catch(e){}data.contact={phone:val('contact-phone'),phoneTel:val('contact-phoneTel'),whatsapp:val('contact-whatsapp'),whatsappDigits:val('contact-whatsappDigits'),email:val('contact-email'),address:val('contact-address'),addressLine1:val('contact-addressLine1'),city:val('contact-city'),region:val('contact-region'),postal:val('contact-postal'),hours:val('contact-hours')};data.seo={title:val('seo-title'),description:val('seo-description'),keywords:val('seo-keywords'),canonical:val('seo-canonical'),ogTitle:val('seo-ogTitle'),ogDescription:val('seo-ogDescription'),ogImage:val('seo-ogImage'),twitterTitle:val('seo-twitterTitle'),twitterDescription:val('seo-twitterDescription'),twitterImage:val('seo-twitterImage')};data.location={name:val('loc-name'),address:val('loc-address'),city:val('loc-city'),region:val('loc-region'),postal:val('loc-postal'),lat:val('loc-lat'),lng:val('loc-lng'),geoRegion:val('loc-geoRegion')};data.services=collectServices();data.nav={main:collectNav('main'),footer:collectNav('footer'),services:collectNav('services')};data.pages=window._pagesSeo||{};return data}
async function saveAll(){const data=collect();localStorage.setItem('teg_content',JSON.stringify(data));cache=data;if(serverMode){try{await TEG.saveContentServer(data);window._servicesCache=Array.isArray(data.services)?JSON.parse(JSON.stringify(data.services)):[];showToast('Saved to server ✓');return}catch(e){showToast('Server save failed — saved locally')}}else showToast('Saved locally')}
async function serverUpload(input,fieldId,previewId){const file=input.files&&input.files[0];if(!file)return;if(!serverMode){showToast('Start server to upload');return}try{showToast('Uploading…');const url=await TEG.uploadFile(file);if(fieldId){const el=document.getElementById(fieldId);if(el)el.value=url}if(previewId){const img=document.getElementById(previewId);if(img){img.src=url;img.classList.add('show')}}showToast('Uploaded ✓')}catch(e){showToast('Upload failed')}}
async function uploadInto(input,targetInput){const file=input.files&&input.files[0];if(!file||!targetInput)return;if(!serverMode){showToast('Start server to upload');return}try{showToast('Uploading…');const url=await TEG.uploadFile(file);targetInput.value=url;showToast('Uploaded ✓')}catch(e){showToast('Upload failed')}}
function renderServices(list){const box=document.getElementById('servicesList');if(!box)return;box.innerHTML='';(list||[]).forEach((svc,i)=>{const div=document.createElement('div');div.className='service-item';div.innerHTML='<button type="button" class="remove" onclick="this.parentElement.remove()">×</button><div class="form-group"><label>Name</label><input class="svc-name" value="'+esc(svc.name||'')+'" /></div><div class="form-group"><label>Description</label><textarea class="svc-desc" rows="2">'+esc(svc.description||'')+'</textarea></div><div class="form-group"><label>Href</label><input class="svc-href" value="'+esc(svc.href||'')+'" /></div><div class="form-group"><label>Service hero image</label><input class="svc-heroImage" value="'+esc(svc.heroImage||'')+'" /></div><div class="upload-box">Upload service hero<br/><input type="file" accept="image/*" onchange="uploadInto(this,this.closest(\'.service-item\').querySelector(\'.svc-heroImage\'))" /></div><div class="form-group"><label>SEO title</label><input class="svc-seoTitle" value="'+esc(svc.seoTitle||'')+'" /></div><div class="form-group"><label>SEO keywords</label><input class="svc-seoKeywords" value="'+esc(svc.seoKeywords||'')+'" /></div><div class="form-group"><label>SEO description</label><textarea class="svc-seoDesc" rows="2">'+esc(svc.seoDescription||'')+'</textarea></div>';box.appendChild(div)})}
function collectServices(){const box=document.getElementById('servicesList');const prev=window._servicesCache||(cache&&Array.isArray(cache.services)?cache.services:[]);if(!box)return prev.map(s=>({...s,beforeAfter:Array.isArray(s.beforeAfter)?s.beforeAfter:[]}));const items=Array.from(box.querySelectorAll('.service-item'));if(!items.length)return prev.map(s=>({...s,beforeAfter:Array.isArray(s.beforeAfter)?s.beforeAfter:[]}));return items.map((el,i)=>{const href=(el.querySelector('.svc-href')||{}).value?el.querySelector('.svc-href').value.trim():'';const old=prev.find(p=>p.href===href)||prev[i]||{};const heroEl=el.querySelector('.svc-heroImage');return{name:(el.querySelector('.svc-name')||{}).value?el.querySelector('.svc-name').value.trim():(old.name||''),description:(el.querySelector('.svc-desc')||{}).value?el.querySelector('.svc-desc').value.trim():(old.description||''),href:href||old.href||'',seoTitle:(el.querySelector('.svc-seoTitle')||{}).value?el.querySelector('.svc-seoTitle').value.trim():(old.seoTitle||''),seoKeywords:(el.querySelector('.svc-seoKeywords')||{}).value?el.querySelector('.svc-seoKeywords').value.trim():(old.seoKeywords||''),seoDescription:(el.querySelector('.svc-seoDesc')||{}).value?el.querySelector('.svc-seoDesc').value.trim():(old.seoDescription||''),heroImage:heroEl&&heroEl.value.trim()?heroEl.value.trim():(old.heroImage||''),beforeAfter:Array.isArray(old.beforeAfter)?old.beforeAfter:[]}})}
function addService(){const list=collectServices();list.push({name:'New service',description:'',href:'services.html',seoTitle:'',seoKeywords:'',seoDescription:'',heroImage:'',beforeAfter:[]});window._servicesCache=list;renderServices(list)}
function renderBeforeAfterPanel(){closeSidebar();const box=document.getElementById('baAllServices');if(!box)return;let services=[];if(window._servicesCache&&window._servicesCache.length){services=window._servicesCache}else if(cache&&Array.isArray(cache.services)){services=JSON.parse(JSON.stringify(cache.services));window._servicesCache=services}else{services=collectServices();window._servicesCache=services}if(!services.length){box.innerHTML='<p class="desc">No services found. Add services first under Services + SEO.</p>';return}box.innerHTML=services.map((svc,si)=>{const pairs=Array.isArray(svc.beforeAfter)?svc.beforeAfter:[];const pairsHtml=pairs.length?pairs.map((p,pi)=>baPairHtml(si,pi,p)).join(''):'<p class="desc" style="margin:8px 0">No pairs yet for this service.</p>';return '<div class="ba-service-block" data-si="'+si+'"><h3>'+esc(svc.name||svc.href||('Service '+(si+1)))+' <span>'+pairs.length+' pair'+(pairs.length===1?'':'s')+'</span></h3><div class="ba-pairs" data-si="'+si+'">'+pairsHtml+'</div><button type="button" class="btn btn-outline btn-sm" onclick="addBaPairFor('+si+')">+ Add pair for this service</button></div>'}).join('')}
function baPairHtml(si,pi,p){p=p||{};const before=p.before||'',after=p.after||'',cap=p.caption||'';const bPrev=before?'<img src="'+esc(before)+'" alt="before" onerror="this.style.display=\'none\'" />':'<div class="thumb-empty">Before</div>';const aPrev=after?'<img src="'+esc(after)+'" alt="after" onerror="this.style.display=\'none\'" />':'<div class="thumb-empty">After</div>';return '<div class="service-item ba-pair-item" data-si="'+si+'" data-pi="'+pi+'"><button type="button" class="remove" onclick="removeBaPairFor('+si+','+pi+')" title="Remove pair">×</button><div class="form-row"><div class="form-group"><label>Before URL</label><input class="ba-before" value="'+esc(before)+'" onchange="syncBaFromDom()" /></div><div class="form-group"><label>After URL</label><input class="ba-after" value="'+esc(after)+'" onchange="syncBaFromDom()" /></div></div><div class="upload-box">Upload before <input type="file" accept="image/*" onchange="uploadInto(this,this.closest(\'.ba-pair-item\').querySelector(\'.ba-before\'));setTimeout(function(){syncBaFromDom();renderBeforeAfterPanel()},400)" /> · Upload after <input type="file" accept="image/*" onchange="uploadInto(this,this.closest(\'.ba-pair-item\').querySelector(\'.ba-after\'));setTimeout(function(){syncBaFromDom();renderBeforeAfterPanel()},400)" /></div><div class="ba-previews">'+bPrev+aPrev+'</div><div class="form-group"><label>Caption (optional)</label><input class="ba-caption" value="'+esc(cap)+'" onchange="syncBaFromDom()" /></div></div>'}
function addBaPairFor(si){syncBaFromDom();const services=window._servicesCache||[];if(!services[si])return;if(!Array.isArray(services[si].beforeAfter))services[si].beforeAfter=[];services[si].beforeAfter.push({before:'',after:'',caption:''});window._servicesCache=services;renderBeforeAfterPanel()}
function removeBaPairFor(si,pi){syncBaFromDom();const services=window._servicesCache||[];if(!services[si]||!Array.isArray(services[si].beforeAfter))return;services[si].beforeAfter.splice(pi,1);window._servicesCache=services;renderBeforeAfterPanel()}
function syncBaFromDom(){const services=window._servicesCache||(cache&&cache.services?JSON.parse(JSON.stringify(cache.services)):collectServices());if(!services.length)return;document.querySelectorAll('.ba-service-block').forEach(block=>{const si=parseInt(block.getAttribute('data-si'),10);if(isNaN(si)||!services[si])return;const pairs=[];block.querySelectorAll('.ba-pair-item').forEach(el=>{pairs.push({before:(el.querySelector('.ba-before')||{}).value||'',after:(el.querySelector('.ba-after')||{}).value||'',caption:(el.querySelector('.ba-caption')||{}).value||''})});services[si].beforeAfter=pairs});window._servicesCache=services}
function saveBaThenAll(){syncBaFromDom();return saveAll()}
function renderBaPairs(){renderBeforeAfterPanel()}
function addBaPair(){const services=window._servicesCache||[];if(services.length)addBaPairFor(0)}
function removeBaPair(i){}
function navListId(cat){return cat==='main'?'navMainList':cat==='footer'?'navFooterList':'navServicesList'}
function renderNav(cat,items){const box=document.getElementById(navListId(cat));if(!box)return;box.innerHTML='';(items||[]).forEach(item=>{const div=document.createElement('div');div.className='nav-item';div.innerHTML='<button type="button" class="remove" onclick="this.parentElement.remove()">×</button><div class="form-row"><div class="form-group"><label>Label</label><input class="nav-label" value="'+esc(item.label||'')+'" /></div><div class="form-group"><label>URL</label><input class="nav-href" value="'+esc(item.href||'')+'" /></div></div>';box.appendChild(div)})}
function collectNav(cat){const box=document.getElementById(navListId(cat));if(!box)return[];return Array.from(box.querySelectorAll('.nav-item')).map(el=>({label:(el.querySelector('.nav-label')||{}).value||'',href:(el.querySelector('.nav-href')||{}).value||''}))}
function addNavItem(cat){const items=collectNav(cat);items.push({label:'New',href:'#'});renderNav(cat,items)}
function loadPageSeoFields(){const page=val('pageSeoSelect')||'index.html';const pages=window._pagesSeo||{};const p=pages[page]||{};set('page-title',p.title||'');set('page-description',p.description||'');set('page-keywords',p.keywords||'');set('page-canonical',p.canonical||'')}
function savePageSeoThenAll(){const page=val('pageSeoSelect')||'index.html';if(!window._pagesSeo)window._pagesSeo={};window._pagesSeo[page]={title:val('page-title'),description:val('page-description'),keywords:val('page-keywords'),canonical:val('page-canonical')};return saveAll()}
function clearPageSeo(){set('page-title','');set('page-description','');set('page-keywords','');set('page-canonical','')}
async function loadInbox(){const box=document.getElementById('inboxList');if(!box)return;if(!serverMode){box.innerHTML='<p class="desc">Server mode required</p>';return}try{const items=await TEG.loadSubmissions();if(!items||!items.length){box.innerHTML='<p class="desc">No submissions yet</p>';return}box.innerHTML=items.map(s=>'<div class="sub-card"><h4>'+esc(s.name||'Lead')+'</h4><p>'+esc(s.phone||'')+' · '+esc(s.email||'')+'</p><p>'+esc(s.message||s.service||'')+'</p></div>').join('')}catch(e){box.innerHTML='<p class="desc">Could not load inbox</p>'}}
function exportJSON(){const data=collect();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='teg-content.json';a.click()}
(async function init(){const key=sessionStorage.getItem('teg_admin');if(key){try{if(await TEG.loginServer(key)){serverMode=true;document.getElementById('loginScreen').classList.add('hidden');document.getElementById('dashboard').classList.add('active');document.getElementById('serverBadge').style.display='inline-block';await load();return}}catch(e){}}})();
